[package]
name = "launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = "_"

[dev-addresses]
launchpad_addr = "0x100"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }

[dev-dependencies]
